### ISSUE TITLE
Erro in subtitles_to_seguencer

### ISSUE THREAD

**Issue by regivaldobep** [doakey3/Subsimport#17]
I saw that the problem with the flame_start function that asks for an integer value instead of a float has already been fix, but for some reason even with the variable strip_start = int(round(start_time * fps, 0)) that is, having a value int, the console keeps showing the same type of error when I try to import some subtitles.
the error that appears is that:

Python: Traceback (most recent call last):
  File "C:\Users\regiv\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Subsimport\operators\import_subtitles.py", line 78, in execute
    strips = subtitles_to_sequencer(context, subs)
  File "C:\Users\regiv\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Subsimport\operators\tools\subtitles_to_sequencer.py", line 36, in subtitles_to_sequencer
    text_strip = scene.sequence_editor.sequences.new_effect(
TypeError: SequencesTopLevel.new_effect(): error with keyword argument "frame_start" -  Function.frame_start expected an int type, not float

**Comment by arieltools** [comment]
Confirming this happening with Blender 3.5 and latest Subsimport.

**Comment by Bl4ckh34d** [comment]
Not yet fixes. Same error with Blender 4.0

**Comment by winne617** [comment]
hey Daniel, any news on this issue?
addon is quite useless without text. what can we do? thx
