### ISSUE TITLE
Syllabify error - out of index on remove punctuation

### ISSUE THREAD

**Issue by JonatasAmaral** [doakey3/Subsimport#2]
When i try to sillabify my subtitles, i'm getting an error of `out of index`, being trowed by the `remove_punctuation` script. I am not an expert, but it looks to me, according to the part `word[0]` that it is happening when some recognized word is "empty". But i tried remove the empty lines of my **.txt** file (just in case the script was using it instead of the Blender's text strips), and it still getting this error

I using _Portuguese_ (there is a lot of accentuation). Tried use the script in _Us english_, even the text being in _Portuguese_. The same.

And i just tied another project from zero to test. Text in english, US english set in the idiom dropdown. Works great.

Here's the console error:
```
Traceback (most recent call last):
  File "C:\Users\jonatas\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Subsimport-master\operators\syllabify.py", line 72, in execute
    words = collect_words(scene)
  File "C:\Users\jonatas\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Subsimport-master\operators\syllabify.py", line 33, in collect_words
    words[i] = remove_punctuation(words[i])
  File "C:\Users\jonatas\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Subsimport-master\operators\tools\remove_punctuation.py", line 8, in remove_punctuation
    while word[0] in puncs:
IndexError: string index out of range

location: <unknown location>:-1

location: <unknown location>:-1
```

**Comment by JonatasAmaral** [comment]
doing some tests, with a new small file, and got a different error:

![screenshot](https://user-images.githubusercontent.com/8677724/31804709-034a7f32-b53a-11e7-9bc2-954720a0de9f.png)
```
Traceback (most recent call last):
  File "C:\Users\jonatas\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Subsimport-master\operators\syllabify.py", line 89, in execute
    hyphenator.setup_patterns()
  File "C:\Users\jonatas\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Subsimport-master\operators\hyphenator\hyphenator.py", line 11, in setup_patterns
    self._insert_pattern(pattern)
  File "C:\Users\jonatas\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Subsimport-master\operators\hyphenator\hyphenator.py", line 22, in _insert_pattern
    points = [ int(d or 0) for d in re.split("[.a-z]", pattern) ]
  File "C:\Users\jonatas\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Subsimport-master\operators\hyphenator\hyphenator.py", line 22, in <listcomp>
    points = [ int(d or 0) for d in re.split("[.a-z]", pattern) ]
ValueError: invalid literal for int() with base 10: '├í'

location: <unknown location>:-1

location: <unknown location>:-1
```

Tried set the idiom to US english, with a portuguese text with accentuations and all those thing, and it works (in the Portuguese idiom it do not). But the main file that i'm working on still getting the first error.

**Comment by doakey3** [comment]
Can you send me the lyrics file you are working with (portuguese is fine) that causes the problem. I'll try to tackle this in the next couple days.

**Comment by JonatasAmaral** [comment]
[letra.txt](text with music's lyrics)

[letra.srt](SRT file exported by the add-on) (it is as TXT because GitHub does'tn support upload SRT files. Just remove .txt from file name)

**Comment by JonatasAmaral** [comment]
[letra.txt](https://github.com/doakey3/Subsimport/files/1424615/letra.txt) - text with music's lyrics used to import into add-on
[letra.srt](https://github.com/doakey3/Subsimport/files/1424617/letra.srt.txt) - SRT file exported by the add-on (it is as TXT because GitHub does'tn support upload SRT files. Just remove .txt from file name)

**Comment by doakey3** [comment]
I've made an update that I think will fix the issue you were having. Thanks for contributing! Sorry I didn't get back to you sooner.

**Comment by JonatasAmaral** [comment]
No problem. I already did what i needed.
I really don't NEEDED the "sillabification" right now. Just posted the issue to help improve the amazing add-on.
Thanks for that.
