### ISSUE TITLE
type error with frame_start

### ISSUE THREAD

**Issue by exitrip** [doakey3/Subsimport#9]
Quite possibly a Blender version problem, but hoping a int to float would be a trivial fix.

```
Python: Traceback (most recent call last):
  File "C:\Users\firee\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Subsimport-master\operators\import_subtitles.py", line 78, in execute
    strips = subtitles_to_sequencer(context, subs)
  File "C:\Users\firee\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Subsimport-master\operators\tools\subtitles_to_sequencer.py", line 36, in subtitles_to_sequencer
    text_strip = scene.sequence_editor.sequences.new_effect(
TypeError: SequencesTopLevel.new_effect(): error with keyword argument "frame_start" -  Function.frame_start expected an int type, not float

location: <unknown location>:-1

```

**Comment by exitrip** [comment]
Looking at subtitles_to_sequencer.py I'm realizing that it would be right to mention that I'm trying to import a raw text file, not a timed sub file

**Comment by exitrip** [comment]
```
        text_strip = scene.sequence_editor.sequences.new_effect(
            name=sub_name,
            type='TEXT',
            channel=open_channel,
            frame_start=int(strip_start),
            frame_end=int(strip_end)
            )
```
Works!   At very least the Dur/2 and Dur*2 need a forced type to work as well...  Python how far you've fallen.

Not gonna PR anything, but I will leave this breadcrumb issue for any wayward traveller.  Tested on Blender 3.1.0 with these small modifications.

**Comment by doakey3** [comment]
Thanks for submitting the issue. I've added your changes to the code.
